name: Prod code
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: installing dependecies
      run: npm install
      
    - name: installing node packege
      run: node compress-images
    - name: compress images
      run: node compress-images
    - name: generate-html-for-prod
      run: |
          gulp minhtml
          gulp mincss
